# Generated by Django 4.1.4 on 2023-01-31 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('useraddress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=100)),
                ('foodprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('cutomername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
                ('foodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.fooditem')),
            ],
        ),
    ]
